name: btc-wallet-tracking
base: core22
version: '1.0.0'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

icon: snap/gui/logo.png  
title: BTC Wallet Tracking

grade: devel # devel / stable
confinement: devmode # devmode / strict

architectures:
  - build-on: amd64

apps:
  btc-wallet-tracking:
    command: snap/command-chain/desktop-launch $SNAP/bin/btc-wallet-tracking
    # environment:
      # PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/src
    plugs:
      - network

    extensions:
      - gnome

parts:
  btc-wallet-tracking:
    plugin: python
    source: .