name: btc-wallet-tracking
base: core22
version: '1.0.0'
summary: BTC Wallet Tracking App
description: |
  This is a simple wallet tracking app built with Python and PyQt.
  

icon: snap/gui/logo.png  
title: BTC Wallet Tracking

grade: stable # devel / stable
confinement: strict # devmode / strict

architectures:
  - build-on: amd64

apps:
  btc-wallet-tracking:
    command: snap/command-chain/desktop-launch $SNAP/bin/btc-wallet-tracking
    plugs:
      - network

    extensions:
      - gnome

parts:
  btc-wallet-tracking:
    plugin: python
    source: .